name: Linting and Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          prettier: true

      - name: Run dependency check
        run: npx depcheck
